Feat/support bignumber
StablePay/sdk_l2 pull request #22
Opened 2020-11-07 22:26 UTC by dmolina79

changes for  #15 

Change Log:
* refactors interface and zkSync Wallet to use BigNumber for balances
* keeps interface compatible with string expectations
* updates unit tests

<img width="1239" alt="Screen Shot 2020-11-07 at 16 24 14" src="https://user-images.githubusercontent.com/6074987/98452561-f302aa00-2115-11eb-800f-d4112ffa4b01.png">

2020-11-08 04:51 UTC, rodyce requested changes

2020-11-08 04:51 UTC, rodyce commented on src/types.ts
> +import { BigNumber } from 'ethers';
I think it is better if we add the dependency to an independent BigNumber library instead of "ethers".

Right now, this project use "ethers" because of zkSync, but the very core base interfaces does not depend on it. In the future, as this project grows we will have to separate core, from the implementation such as zksync Loopring. Futhermore, Loopring may or may not even depend on "ethers"...

2020-11-08 04:53 UTC, rodyce requested changes
Bump version number in package.json to then publish to npm

2020-11-08 14:42 UTC, dmolina79 commented on src/types.ts
> +import { BigNumber } from 'ethers';
i see your point, but i think is fine to depend on ethers since it already uses bignumber.js as a dependency and also gives us all other wallet and provider functionality. If add the bignumber.js library directly we would be duplicating dependencies at EOD and since this library is meant to be used in FE is better to keep it lean so less dependencies the better.

When we integrate other libraries we need to map or transform the outputs to ethers bigNumber if there is an issue, but i don't think it will be the case.

2020-11-09 01:11 UTC, rodyce approved these changes

2020-11-09 01:14 UTC, merged